version: '3.8'

services:
  ros-dev-environment:
    context: ..
    dockerfile: docker/Dockerfile.dev
    args:
      - "USERNAME=ros"
      - "WORKDIR=libs/"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix"
    network_mode:
      - "host"
    cap-add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp:unconfined"
      - "apparmor:unconfined"
